{"name": "test_should_create_user", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './files/users.csv'", "trace": "self = <test_user_request.TestUser object at 0x00000212B2E65630>\n\n    @allure.feature('should_create_order')\n    def test_should_create_user(self):\n        logger.info(100 * \"=\")\n        logger.info(\"Start test should_create_user()\")\n        logger.info(100 * \"-\")\n>       user = get_random_user_json(\"./files/users.csv\")\n\ntest_api\\user\\test_user_request.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_api\\user\\data\\user.py:35: in get_random_user_json\n    random_index = random.randint(0, len(__get_users_list_from_csv(path)) - 1)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\npath = './files/users.csv'\n\n    def __get_users_list_from_csv(path):\n        users_list = []\n    \n>       with open(path, newline='') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: './files/users.csv'\n\ntest_api\\user\\data\\user.py:24: FileNotFoundError"}, "start": 1700663262577, "stop": 1700663262579, "uuid": "e1183a8a-0c37-4b24-a753-40b0190b4720", "historyId": "9002dbbf285be45e408d6b7caf47c9cf", "testCaseId": "b1d985b069a0b3a92a30183ab4ca8410", "fullName": "test_api.user.test_user_request.TestUser#test_should_create_user", "labels": [{"name": "feature", "value": "should_create_order"}, {"name": "parentSuite", "value": "test_api.user"}, {"name": "suite", "value": "test_user_request"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "DESKTOP-BLGDRF0"}, {"name": "thread", "value": "10148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.user.test_user_request"}]}