{"name": "test_should_update_user", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'files/users.csv'", "trace": "self = <test_user_request.TestUser object at 0x00000212B4FDB610>\n\n    @allure.feature('should_update_user')\n    def test_should_update_user(self):\n        logger.info(100 * \"=\")\n        logger.info(\"Start test should_update_user()\")\n        logger.info(100 * \"-\")\n>       user = get_random_user_json(\"files/users.csv\")\n\ntest_api\\user\\test_user_request.py:58: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_api\\user\\data\\user.py:35: in get_random_user_json\n    random_index = random.randint(0, len(__get_users_list_from_csv(path)) - 1)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\npath = 'files/users.csv'\n\n    def __get_users_list_from_csv(path):\n        users_list = []\n    \n>       with open(path, newline='') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'files/users.csv'\n\ntest_api\\user\\data\\user.py:24: FileNotFoundError"}, "start": 1700663263303, "stop": 1700663263304, "uuid": "12503bca-ba50-474f-b20a-4dd3802ecd3e", "historyId": "12515c4e6844fd8822ec7040998ffa01", "testCaseId": "f3d844a16b4b57f818244cb11205aecc", "fullName": "test_api.user.test_user_request.TestUser#test_should_update_user", "labels": [{"name": "feature", "value": "should_update_user"}, {"name": "parentSuite", "value": "test_api.user"}, {"name": "suite", "value": "test_user_request"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "DESKTOP-BLGDRF0"}, {"name": "thread", "value": "10148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.user.test_user_request"}]}